package main.interfaz;

import java.awt.Color;

/**
 *
 * @author marco
 */
public class LoginAdmin extends javax.swing.JPanel {

    /**
     * Creates new form LoginAdmin
     */
    java.awt.Font fuente = new java.awt.Font("FreeMono", java.awt.Font.PLAIN, 18);

    public LoginAdmin() {
        initComponents();
        txtUser.setText("Ingrese su Nombre");
        txtUser.setForeground(Color.gray);
        txtUser.setFont(fuente);
        txtPass.setText("Ingrese su Contraseña");
        txtPass.setForeground(Color.gray);
        txtPass.setEchoChar((char) 0);
        txtPass.setFont(fuente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        user = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        bg_login = new javax.swing.JPanel();
        bt_Login = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(242, 140, 40));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtUser.setForeground(new java.awt.Color(153, 153, 153));
        txtUser.setBorder(null);
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });
        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });
        jPanel2.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 310, 30));

        txtPass.setText("jPasswordField1");
        txtPass.setBorder(null);
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassFocusLost(evt);
            }
        });
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        jPanel2.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 310, 40));

        user.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        user.setForeground(new java.awt.Color(0, 0, 0));
        user.setText("Usuario");
        jPanel2.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        password.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        password.setForeground(new java.awt.Color(0, 0, 0));
        password.setText("Password");
        jPanel2.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        bg_login.setBackground(new java.awt.Color(255, 85, 30));

        bt_Login.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        bt_Login.setForeground(new java.awt.Color(255, 255, 255));
        bt_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_Login.setText("Entrar");
        bt_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_LoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_LoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_LoginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bg_loginLayout = new javax.swing.GroupLayout(bg_login);
        bg_login.setLayout(bg_loginLayout);
        bg_loginLayout.setHorizontalGroup(
            bg_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_Login, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        bg_loginLayout.setVerticalGroup(
            bg_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_loginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(bg_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 150, 50));
        jPanel2.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 410, 30));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Login Admin");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 480, 530));

        jPanel3.setBackground(new java.awt.Color(255, 85, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gym_System");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gym3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel2)
                .addGap(66, 66, 66)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 320, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void reinicioUser(){
        if (txtUser.getText().isEmpty()) {
            txtUser.setText("Ingrese su Nombre");
            txtUser.setForeground(Color.gray);
        }
    }
    
    public void reinicioPass() {
        String pass = String.valueOf(txtPass.getPassword());
        if (pass.isEmpty()) {
            txtPass.setText("Ingrese su Contraseña");
            txtPass.setForeground(Color.gray);
            txtPass.setEchoChar((char) 0);
        }
    }
    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        // TODO add your handling code here:
        if (txtUser.getText().equals("Ingrese su Nombre")) {
            txtUser.setText("");
            txtUser.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtUserFocusGained

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
        // TODO add your handling code here:
        reinicioUser();
    }//GEN-LAST:event_txtUserFocusLost

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained
        // TODO add your handling code here:
        String pass = String.valueOf(txtPass.getPassword());
        if (pass.equals("Ingrese su Contraseña")) {
            txtPass.setText("");
            txtPass.setForeground(Color.black);
            txtPass.setEchoChar('*');
        }
    }//GEN-LAST:event_txtPassFocusGained

    private void txtPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusLost
        // TODO add your handling code here:
        reinicioPass();
    }//GEN-LAST:event_txtPassFocusLost

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void bt_LoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_LoginMouseEntered
        // TODO add your handling code here:
        bg_login.setBackground(new Color(242,140,40));
        bt_Login.setForeground(Color.white);
    }//GEN-LAST:event_bt_LoginMouseEntered

    private void bt_LoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_LoginMouseExited
        // TODO add your handling code here:
        bg_login.setBackground(new Color(204,85,51));
        bt_Login.setForeground(Color.white);
    }//GEN-LAST:event_bt_LoginMouseExited

    private void bt_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_LoginMouseClicked
        // TODO add your handling code here:
        String usuario = txtUser.getText();
        String password = String.valueOf(txtPass.getPassword());

        if (usuario.equals("Marco") && password.equals("123456")) {
            error.setText("");
            Admin admin = new Admin();
            admin.setSize(1000, 600);
            admin.setLocation(0, 0);

            java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);
            if (parentWindow instanceof javax.swing.JFrame) {
                javax.swing.JFrame frame = (javax.swing.JFrame) parentWindow;
                frame.getContentPane().removeAll();
                frame.getContentPane().add(admin);
                frame.getContentPane().revalidate();
                frame.getContentPane().repaint();
            }
        } else {
            error.setText("Usuario y Contraseña Incorrectas");
            error.setForeground(Color.red);
            error.setFont(fuente);
            txtUser.setText("");
            txtPass.setText("");
            reinicioUser();
            reinicioPass();
        }
    }//GEN-LAST:event_bt_LoginMouseClicked

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_login;
    private javax.swing.JLabel bt_Login;
    private javax.swing.JLabel error;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
