package main.interfaz;

import java.awt.Color;
import main.dao.EmpleadoDao;
import main.interfaz.empleado.Recepcionista;
import main.models.Empleado;
import main.utils.Utils;

/**
 *
 * @author marco
 */
public class LoginEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form LoginEmpleado
     */
    java.awt.Font fuente = new java.awt.Font("FreeMono", java.awt.Font.BOLD, 18);
    
    int rol;
    
    public LoginEmpleado(String worker, int roles) {
        initComponents();
        LOGIN.setText("");
        txtError.setText("");
        LOGIN.setText(worker);
        rol = roles;
        txtUser.setText("Ingrese su Nombre");
        txtUser.setForeground(Color.gray);
        txtUser.setFont(fuente);
        txtPass.setText("Ingrese su Contraseña");
        txtPass.setForeground(Color.gray);
        txtPass.setEchoChar((char) 0);
        txtPass.setFont(fuente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_Atras = new javax.swing.JLabel();
        LOGIN = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        bg_login = new javax.swing.JPanel();
        bt_login = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        txtError = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 85, 30));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gym3.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("FreeMono", 1, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bienvenido a Gym_System");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(103, 103, 103))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 600));

        bt_Atras.setBackground(new java.awt.Color(255, 85, 30));
        bt_Atras.setFont(new java.awt.Font("FreeMono", 1, 28)); // NOI18N
        bt_Atras.setForeground(new java.awt.Color(255, 85, 30));
        bt_Atras.setText("atras");
        bt_Atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Atras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_AtrasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_AtrasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_AtrasMouseExited(evt);
            }
        });
        jPanel1.add(bt_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 560, -1, -1));

        LOGIN.setBackground(new java.awt.Color(255, 85, 30));
        LOGIN.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        LOGIN.setForeground(new java.awt.Color(255, 85, 30));
        LOGIN.setText("Login");
        jPanel1.add(LOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 85, 30));
        jLabel5.setFont(new java.awt.Font("FreeMono", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 85, 30));
        jLabel5.setText("Nombre");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, -1, -1));

        txtUser.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        txtUser.setForeground(new java.awt.Color(0, 0, 0));
        txtUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 85, 30)));
        txtUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUserFocusLost(evt);
            }
        });
        jPanel1.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 280, 30));

        bg_login.setBackground(new java.awt.Color(255, 85, 30));

        bt_login.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_login.setForeground(new java.awt.Color(255, 255, 255));
        bt_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bt_login.setText("entrar");
        bt_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_loginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bg_loginLayout = new javax.swing.GroupLayout(bg_login);
        bg_login.setLayout(bg_loginLayout);
        bg_loginLayout.setHorizontalGroup(
            bg_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_login, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );
        bg_loginLayout.setVerticalGroup(
            bg_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bt_login, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(bg_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 500, 110, 40));

        jLabel4.setBackground(new java.awt.Color(255, 85, 30));
        jLabel4.setFont(new java.awt.Font("FreeMono", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 85, 30));
        jLabel4.setText("Password");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, -1));

        txtPass.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        txtPass.setForeground(new java.awt.Color(0, 0, 0));
        txtPass.setText("jPasswordField1");
        txtPass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 85, 30)));
        txtPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassFocusLost(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 280, 30));

        txtError.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        txtError.setForeground(new java.awt.Color(255, 0, 0));
        txtError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtError.setText("Usuario y contaseña Incorrectos");
        jPanel1.add(txtError, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 450, 380, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void reinicioUser(){
        if (txtUser.getText().isEmpty()) {
            txtUser.setText("Ingrese su Nombre");
            txtUser.setForeground(Color.gray);
        }
    }
    
    public void reinicioPass() {
        String pass = String.valueOf(txtPass.getPassword());
        if (pass.isEmpty()) {
            txtPass.setText("Ingrese su Contraseña");
            txtPass.setForeground(Color.gray);
            txtPass.setEchoChar((char) 0);
        }
    }
    
    private void bt_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseClicked
        // TODO add your handling code here:
        String usuario = txtUser.getText();
        String password = String.valueOf(txtPass.getPassword());
        
        EmpleadoDao dao = new EmpleadoDao();
        Empleado emp = dao.loginEmpleado(usuario, password);
        
        if (emp != null) {
            int logRol = emp.getIdRol();
            if (logRol == rol) {
                switch (logRol) {
                    case 1:
                        Utils.cambiarPanel(this, new Recepcionista(usuario));
                        break;
                    case 2:
                        txtError.setText("Entrenador");
                        break;
                    case 3:
                        txtError.setText("Inventario");
                        break;
                    default:
                        throw new AssertionError();
                }
            } else {
                txtError.setText("Rol de Login Incorrecto");
            }
        } else {
            txtError.setText("Usuario o Contraseña Incorrectas");
        }
    }//GEN-LAST:event_bt_loginMouseClicked

    private void bt_loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseEntered
        // TODO add your handling code here:
        bg_login.setBackground(new Color(242,140,40));
        bt_login.setForeground(Color.white);
    }//GEN-LAST:event_bt_loginMouseEntered

    private void bt_loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_loginMouseExited
        // TODO add your handling code here:
        bg_login.setBackground(new Color(204,85,51));
        bt_login.setForeground(Color.white);
    }//GEN-LAST:event_bt_loginMouseExited

    private void bt_AtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AtrasMouseClicked
        // TODO add your handling code here:
        Utils.cambiarPanel(this, new Roles());
    }//GEN-LAST:event_bt_AtrasMouseClicked

    private void bt_AtrasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AtrasMouseEntered
        // TODO add your handling code here:
        bt_Atras.setForeground(new Color(204,85,51));
    }//GEN-LAST:event_bt_AtrasMouseEntered

    private void bt_AtrasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AtrasMouseExited
        // TODO add your handling code here:
        bt_Atras.setForeground(new Color(255, 85, 30));
    }//GEN-LAST:event_bt_AtrasMouseExited

    private void txtUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusGained
        // TODO add your handling code here:
        if (txtUser.getText().equals("Ingrese su Nombre")) {
            txtUser.setText("");
            txtUser.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtUserFocusGained

    private void txtUserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserFocusLost
        // TODO add your handling code here:
        reinicioUser();
    }//GEN-LAST:event_txtUserFocusLost

    private void txtPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusGained
        // TODO add your handling code here:
        String pass = String.valueOf(txtPass.getPassword());
        if (pass.equals("Ingrese su Contraseña")) {
            txtPass.setText("");
            txtPass.setForeground(Color.black);
            txtPass.setEchoChar('*');
        }
    }//GEN-LAST:event_txtPassFocusGained

    private void txtPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassFocusLost
        // TODO add your handling code here:
        reinicioPass();
    }//GEN-LAST:event_txtPassFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGIN;
    private javax.swing.JPanel bg_login;
    private javax.swing.JLabel bt_Atras;
    private javax.swing.JLabel bt_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtError;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
