package main.interfaz.empleado;

import java.util.List;
import javax.swing.JOptionPane;
import main.models.Empleado;
import main.models.Entrenador_Cliente;
import main.dao.EmpleadoDao;
import main.dao.Entrenador_ClienteDao;
import main.utils.Utils;

/**
 *
 * @author marco
 */
public class Asignar extends javax.swing.JPanel {

    /**
     * Creates new form Asignar
     */
    
    EmpleadoDao dao = new EmpleadoDao();
    Entrenador_ClienteDao enCiDao = new Entrenador_ClienteDao();
    private long dpi_cliente;
    
    public Asignar(long dpi) {
        initComponents();
        String strDPI = Long.toString(dpi);
        txt_DPI.setText(strDPI);
        cargarCoach();
        dpi_cliente = dpi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puerta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_DPI = new javax.swing.JTextPane();
        com_Coach = new javax.swing.JComboBox<>();
        txt_FechaInicio = new javax.swing.JTextField();
        txt_FechaFin = new javax.swing.JTextField();
        bt_Asignar = new javax.swing.JButton();
        bt_Cancelar = new javax.swing.JButton();

        puerta.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Asignar Entrenador");

        jLabel2.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Entrenador");

        jLabel3.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("DPI");

        jLabel4.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha Inicio");

        jLabel5.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Fecha Fin");

        txt_DPI.setEditable(false);
        txt_DPI.setBackground(new java.awt.Color(255, 255, 255));
        txt_DPI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204)));
        txt_DPI.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        txt_DPI.setForeground(new java.awt.Color(0, 0, 0));
        txt_DPI.setFocusable(false);
        jScrollPane1.setViewportView(txt_DPI);

        com_Coach.setBackground(new java.awt.Color(204, 0, 204));
        com_Coach.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        com_Coach.setForeground(new java.awt.Color(255, 255, 255));
        com_Coach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_CoachActionPerformed(evt);
            }
        });

        txt_FechaInicio.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        txt_FechaInicio.setForeground(new java.awt.Color(0, 0, 0));
        txt_FechaInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204)));

        txt_FechaFin.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        txt_FechaFin.setForeground(new java.awt.Color(0, 0, 0));
        txt_FechaFin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204)));

        bt_Asignar.setBackground(new java.awt.Color(255, 85, 30));
        bt_Asignar.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Asignar.setForeground(new java.awt.Color(255, 255, 255));
        bt_Asignar.setText("asignar");
        bt_Asignar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AsignarActionPerformed(evt);
            }
        });

        bt_Cancelar.setBackground(new java.awt.Color(204, 0, 0));
        bt_Cancelar.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        bt_Cancelar.setText("cancelar");
        bt_Cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout puertaLayout = new javax.swing.GroupLayout(puerta);
        puerta.setLayout(puertaLayout);
        puertaLayout.setHorizontalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(puertaLayout.createSequentialGroup()
                                .addComponent(bt_Cancelar)
                                .addGap(18, 18, 18)
                                .addComponent(bt_Asignar))
                            .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(puertaLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_FechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(111, 111, 111)
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_FechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1)
                                .addGroup(puertaLayout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(com_Coach, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(92, 92, Short.MAX_VALUE))
        );
        puertaLayout.setVerticalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(com_Coach, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txt_FechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_FechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Asignar)
                    .addComponent(bt_Cancelar))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_AsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AsignarActionPerformed
        // TODO add your handling code here:
        String fechaInicio = txt_FechaInicio.getText().trim();
        String fechaFin = txt_FechaFin.getText().trim();
        
        if (fechaInicio.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes ingresar fecha de inicio");
            return;
        }
        
        if (fechaFin.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes ingresar fecha de fin");
            return;
        }
        java.sql.Date fechaInicioSQL;
        java.sql.Date fechaFinSQL;
        try {
            fechaInicioSQL = java.sql.Date.valueOf(fechaInicio);
            fechaFinSQL = java.sql.Date.valueOf(fechaFin);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this,
                    "Formato de fecha inválido. Usa yyyy-MM-dd");
            return;
        }
        
        Empleado selec = (Empleado) com_Coach.getSelectedItem();
        if (selec == null) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un entrenador");
            return;
        }
        
        long dpi_entrenador = selec.getDpi();
        
        Entrenador_Cliente enCi = new Entrenador_Cliente(dpi_entrenador, dpi_cliente, fechaInicioSQL, fechaFinSQL);
        enCiDao.crear(enCi);
        JOptionPane.showMessageDialog(this, "Asignacion Creada");
        Utils.mostrarPanel(puerta, new ListaClientes());
    }//GEN-LAST:event_bt_AsignarActionPerformed

    private void com_CoachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_CoachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_CoachActionPerformed

    private void bt_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelarActionPerformed
        // TODO add your handling code here:
        Utils.mostrarPanel(puerta, new ListaClientes());
    }//GEN-LAST:event_bt_CancelarActionPerformed
    
    private void cargarCoach() {
        com_Coach.removeAllItems();
        List<Empleado> lista = dao.listar();
        int sucursal = Utils.datosEmpleado(Recepcionista.usuario);
        
        for (Empleado emp : lista) {
            if (emp.getIdRol() == 2 && emp.getIdSucursal() == sucursal) {
                com_Coach.addItem(emp);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Asignar;
    private javax.swing.JButton bt_Cancelar;
    private javax.swing.JComboBox<Empleado> com_Coach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel puerta;
    private javax.swing.JTextPane txt_DPI;
    private javax.swing.JTextField txt_FechaFin;
    private javax.swing.JTextField txt_FechaInicio;
    // End of variables declaration//GEN-END:variables
}
