package main.interfaz.empleado;

import java.awt.Color;
import javax.swing.JOptionPane;
import main.dao.EmpleadoDao;
import main.interfaz.Roles;
import main.interfaz.empleado.entrenador.*;
import main.models.Empleado;
import main.utils.Utils;

/**
 *
 * @author marco
 */
public class Entrenador extends javax.swing.JPanel {

    /**
     * Creates new form Entrenador
     */
    
    EmpleadoDao dao = new EmpleadoDao();
    
    private long edpi;
    
    public Entrenador(String usuario, long dpi) {
        initComponents();
        edpi = dpi;
        txtUser.setText("");
        txtUser.setText(usuario);
        Utils.mostrarPanel(puerta, new lista_Clientes(edpi));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bt_Clientes = new javax.swing.JLabel();
        bt_Rutinas = new javax.swing.JLabel();
        bt_Asistencias = new javax.swing.JLabel();
        puerta = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra.setBackground(new java.awt.Color(51, 153, 0));
        barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Entrenador");
        barra.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 35, -1, -1));

        txtUser.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtUser.setText("usuario");
        txtUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtUserMouseExited(evt);
            }
        });
        barra.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gym1.png"))); // NOI18N
        barra.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 10, -1, -1));

        bt_Clientes.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        bt_Clientes.setForeground(new java.awt.Color(255, 255, 255));
        bt_Clientes.setText("Clientes");
        bt_Clientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_ClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_ClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_ClientesMouseExited(evt);
            }
        });
        barra.add(bt_Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 87, -1, -1));

        bt_Rutinas.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        bt_Rutinas.setForeground(new java.awt.Color(255, 255, 255));
        bt_Rutinas.setText("Rutinas");
        bt_Rutinas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Rutinas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_RutinasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_RutinasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_RutinasMouseExited(evt);
            }
        });
        barra.add(bt_Rutinas, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 87, -1, -1));

        bt_Asistencias.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        bt_Asistencias.setForeground(new java.awt.Color(255, 255, 255));
        bt_Asistencias.setText("Asistencias");
        bt_Asistencias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Asistencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_AsistenciasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_AsistenciasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_AsistenciasMouseExited(evt);
            }
        });
        barra.add(bt_Asistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 87, -1, -1));

        jPanel1.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 130));

        puerta.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout puertaLayout = new javax.swing.GroupLayout(puerta);
        puerta.setLayout(puertaLayout);
        puertaLayout.setHorizontalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        puertaLayout.setVerticalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel1.add(puerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1000, 470));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        // TODO add your handling code here:
        String usuario = txtUser.getText();
        Empleado emp = dao.perfil(usuario);

        if (emp != null) {
            long dpi = emp.getDpi();
            String nombre = emp.getNombre();
            String apellido = emp.getApellido();
            String telefono = emp.getTelefono();
            String direccion = emp.getDireccion();
            int sucursal = emp.getIdSucursal();
            int rol = emp.getIdRol();
            
            String sdpi = String.valueOf(dpi);
            String sSucursal = Utils.getSucursalNombre(sucursal);
            String sRol = Utils.getRolNombre(rol);
            
            Utils.mostrarPanel(puerta, new Perfil(sdpi, nombre, apellido, telefono, direccion, sSucursal, sRol));

        } else {
            JOptionPane.showMessageDialog(this, "Error de Usuario");
            Utils.cambiarPanel(puerta, new Roles());
        }
    }//GEN-LAST:event_txtUserMouseClicked

    private void txtUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseEntered
        // TODO add your handling code here:
        txtUser.setForeground(new Color(124, 207, 53));
    }//GEN-LAST:event_txtUserMouseEntered

    private void txtUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseExited
        // TODO add your handling code here:
        txtUser.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_txtUserMouseExited

    private void bt_ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ClientesMouseClicked
        // TODO add your handling code here:
        Utils.mostrarPanel(puerta, new lista_Clientes(edpi));
    }//GEN-LAST:event_bt_ClientesMouseClicked

    private void bt_ClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ClientesMouseExited
        // TODO add your handling code here:
        bt_Clientes.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_bt_ClientesMouseExited

    private void bt_ClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ClientesMouseEntered
        // TODO add your handling code here:
        bt_Clientes.setForeground(new Color(124, 207, 53));
    }//GEN-LAST:event_bt_ClientesMouseEntered

    private void bt_RutinasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_RutinasMouseClicked
        // TODO add your handling code here:
        Utils.mostrarPanel(puerta, new lista_Rutinas(edpi));
    }//GEN-LAST:event_bt_RutinasMouseClicked

    private void bt_RutinasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_RutinasMouseEntered
        // TODO add your handling code here:
        bt_Rutinas.setForeground(new Color(124, 207, 53));
    }//GEN-LAST:event_bt_RutinasMouseEntered

    private void bt_RutinasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_RutinasMouseExited
        // TODO add your handling code here:
        bt_Rutinas.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_bt_RutinasMouseExited

    private void bt_AsistenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AsistenciasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_AsistenciasMouseClicked

    private void bt_AsistenciasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AsistenciasMouseEntered
        // TODO add your handling code here:
        bt_Asistencias.setForeground(new Color(124, 207, 53));
    }//GEN-LAST:event_bt_AsistenciasMouseEntered

    private void bt_AsistenciasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AsistenciasMouseExited
        // TODO add your handling code here:
        bt_Asistencias.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_bt_AsistenciasMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra;
    private javax.swing.JLabel bt_Asistencias;
    private javax.swing.JLabel bt_Clientes;
    private javax.swing.JLabel bt_Rutinas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel puerta;
    private javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables
}
