package main.interfaz.empleado;

import java.awt.Color;
import javax.swing.JOptionPane;
import main.dao.EmpleadoDao;
import main.interfaz.Roles;
import main.interfaz.empleado.inventario.*;
import main.models.Empleado;
import main.utils.Utils;

/**
 *
 * @author marco
 */
public class Inventario extends javax.swing.JPanel {

    /**
     * Creates new form Inventario
     */
    
    EmpleadoDao dao = new EmpleadoDao();
    
    public Inventario(String usuario) {
        initComponents();
        txtUser.setText("");
        txtUser.setText(usuario);
        Utils.mostrarPanel(puerta, new Lista_Equipos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_Inventario = new javax.swing.JLabel();
        bt_Equipos = new javax.swing.JLabel();
        bt_Repuestos = new javax.swing.JLabel();
        txtUser = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        puerta = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra.setBackground(new java.awt.Color(20, 71, 230));

        jLabel1.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inventario");

        bt_Inventario.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        bt_Inventario.setForeground(new java.awt.Color(255, 255, 255));
        bt_Inventario.setText("Inventario");
        bt_Inventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Inventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_InventarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_InventarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_InventarioMouseExited(evt);
            }
        });

        bt_Equipos.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        bt_Equipos.setForeground(new java.awt.Color(255, 255, 255));
        bt_Equipos.setText("Equipos");
        bt_Equipos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Equipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_EquiposMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_EquiposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_EquiposMouseExited(evt);
            }
        });

        bt_Repuestos.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        bt_Repuestos.setForeground(new java.awt.Color(255, 255, 255));
        bt_Repuestos.setText("Repuestos");
        bt_Repuestos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Repuestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_RepuestosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_RepuestosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_RepuestosMouseExited(evt);
            }
        });

        txtUser.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtUser.setText("usuario");
        txtUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtUserMouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gym1.png"))); // NOI18N

        javax.swing.GroupLayout barraLayout = new javax.swing.GroupLayout(barra);
        barra.setLayout(barraLayout);
        barraLayout.setHorizontalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLayout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(43, 43, 43))
            .addGroup(barraLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(bt_Equipos)
                .addGap(38, 38, 38)
                .addComponent(bt_Inventario)
                .addGap(27, 27, 27)
                .addComponent(bt_Repuestos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtUser)
                .addGap(32, 32, 32))
        );
        barraLayout.setVerticalGroup(
            barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraLayout.createSequentialGroup()
                .addGroup(barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(barraLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLayout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLayout.createSequentialGroup()
                        .addGroup(barraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_Equipos)
                            .addComponent(bt_Inventario)
                            .addComponent(bt_Repuestos))
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraLayout.createSequentialGroup()
                        .addComponent(txtUser)
                        .addGap(22, 22, 22))))
        );

        jPanel1.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 130));

        puerta.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout puertaLayout = new javax.swing.GroupLayout(puerta);
        puerta.setLayout(puertaLayout);
        puertaLayout.setHorizontalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        puertaLayout.setVerticalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel1.add(puerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1000, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_EquiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_EquiposMouseClicked
        // TODO add your handling code here:
        Utils.mostrarPanel(puerta, new Lista_Equipos());
    }//GEN-LAST:event_bt_EquiposMouseClicked

    private void bt_EquiposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_EquiposMouseEntered
        // TODO add your handling code here:
        bt_Equipos.setForeground(new Color(147, 172, 246));
    }//GEN-LAST:event_bt_EquiposMouseEntered

    private void bt_EquiposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_EquiposMouseExited
        // TODO add your handling code here:
        bt_Equipos.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_bt_EquiposMouseExited

    private void bt_InventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_InventarioMouseClicked
        // TODO add your handling code here:
        Utils.mostrarPanel(puerta, new lista_Inventario());
    }//GEN-LAST:event_bt_InventarioMouseClicked

    private void bt_InventarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_InventarioMouseEntered
        // TODO add your handling code here:
        bt_Inventario.setForeground(new Color(147, 172, 246));
    }//GEN-LAST:event_bt_InventarioMouseEntered

    private void bt_InventarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_InventarioMouseExited
        // TODO add your handling code here:
        bt_Inventario.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_bt_InventarioMouseExited

    private void bt_RepuestosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_RepuestosMouseClicked
        // TODO add your handling code here:
        Utils.mostrarPanel(puerta, new Reportes());
    }//GEN-LAST:event_bt_RepuestosMouseClicked

    private void bt_RepuestosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_RepuestosMouseEntered
        // TODO add your handling code here:
        bt_Repuestos.setForeground(new Color(147, 172, 246));
    }//GEN-LAST:event_bt_RepuestosMouseEntered

    private void bt_RepuestosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_RepuestosMouseExited
        // TODO add your handling code here:
        bt_Repuestos.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_bt_RepuestosMouseExited

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        // TODO add your handling code here:
        String usuario = txtUser.getText();
        Empleado emp = dao.perfil(usuario);

        if (emp != null) {
            long dpi = emp.getDpi();
            String nombre = emp.getNombre();
            String apellido = emp.getApellido();
            String telefono = emp.getTelefono();
            String direccion = emp.getDireccion();
            int sucursal = emp.getIdSucursal();
            int rol = emp.getIdRol();

            String sdpi = String.valueOf(dpi);
            String sSucursal = Utils.getSucursalNombre(sucursal);
            String sRol = Utils.getRolNombre(rol);

            Utils.mostrarPanel(puerta, new Perfil(sdpi, nombre, apellido, telefono, direccion, sSucursal, sRol));

        } else {
            JOptionPane.showMessageDialog(this, "Error de Usuario");
            Utils.cambiarPanel(puerta, new Roles());
        }
    }//GEN-LAST:event_txtUserMouseClicked

    private void txtUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseEntered
        // TODO add your handling code here:
        txtUser.setForeground(new Color(147, 172, 246));
    }//GEN-LAST:event_txtUserMouseEntered

    private void txtUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseExited
        // TODO add your handling code here:
        txtUser.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_txtUserMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra;
    private javax.swing.JLabel bt_Equipos;
    private javax.swing.JLabel bt_Inventario;
    private javax.swing.JLabel bt_Repuestos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel puerta;
    private javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables
}
