package main.interfaz.empleado;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import main.dao.EquipoDao;
import main.models.Equipo;

/**
 *
 * @author marco
 */
public class Lista_Equipos extends javax.swing.JPanel {

    /**
     * Creates new form Lista_Equipos
     */
    
    EquipoDao dao = new EquipoDao();
    
    public Lista_Equipos() {
        initComponents();
        cargarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puerta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_Equipos = new javax.swing.JTable();
        bt_Crear = new javax.swing.JButton();
        bt_Eli = new javax.swing.JButton();
        bt_Mod = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        puerta.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 71, 230));
        jLabel1.setText("Lista de Equipos");

        tab_Equipos.setBackground(new java.awt.Color(20, 71, 230));
        tab_Equipos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tab_Equipos.setFont(new java.awt.Font("FreeMono", 1, 15)); // NOI18N
        tab_Equipos.setForeground(new java.awt.Color(255, 255, 255));
        tab_Equipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Descripcion", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab_Equipos.setFocusable(false);
        jScrollPane1.setViewportView(tab_Equipos);
        if (tab_Equipos.getColumnModel().getColumnCount() > 0) {
            tab_Equipos.getColumnModel().getColumn(0).setMinWidth(100);
            tab_Equipos.getColumnModel().getColumn(0).setMaxWidth(100);
            tab_Equipos.getColumnModel().getColumn(3).setMinWidth(150);
            tab_Equipos.getColumnModel().getColumn(3).setMaxWidth(150);
        }

        bt_Crear.setBackground(new java.awt.Color(51, 204, 0));
        bt_Crear.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Crear.setForeground(new java.awt.Color(0, 0, 0));
        bt_Crear.setText("crear");
        bt_Crear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bt_Eli.setBackground(new java.awt.Color(204, 0, 0));
        bt_Eli.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Eli.setForeground(new java.awt.Color(255, 255, 255));
        bt_Eli.setText("eliminar");
        bt_Eli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bt_Mod.setBackground(new java.awt.Color(255, 255, 51));
        bt_Mod.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Mod.setForeground(new java.awt.Color(0, 0, 0));
        bt_Mod.setText("modificar");
        bt_Mod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ModActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(20, 71, 230));
        jLabel3.setText("Acciones");

        javax.swing.GroupLayout puertaLayout = new javax.swing.GroupLayout(puerta);
        puerta.setLayout(puertaLayout);
        puertaLayout.setHorizontalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 958, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_Crear)
                        .addGap(24, 24, 24))))
            .addGroup(puertaLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addComponent(bt_Mod)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Eli))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        puertaLayout.setVerticalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bt_Crear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Mod)
                    .addComponent(bt_Eli))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_ModActionPerformed
    
    public void cargarLista() {
        DefaultTableModel modelo = (DefaultTableModel) tab_Equipos.getModel();
        modelo.setRowCount(0);
        List<Equipo> lista = dao.listar();

        for (Equipo equi : lista) {
            modelo.addRow(new Object[]{
                equi.getId(),
                equi.getNombre(),
                equi.getDescripcion(),
                equi.getTipo()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Crear;
    private javax.swing.JButton bt_Eli;
    private javax.swing.JButton bt_Mod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel puerta;
    private javax.swing.JTable tab_Equipos;
    // End of variables declaration//GEN-END:variables
}
