package main.interfaz.empleado;

import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.dao.MembresiasDao;
import main.models.Membresia;
import main.models.MembresiaDetalle;
import main.utils.Utils;

/**
 *
 * @author marco
 */
public class Lista_Membresias extends javax.swing.JPanel {

    /**
     * Creates new form Lista_Membresias
     */
    MembresiasDao dao = new MembresiasDao();

    public Lista_Membresias() {
        initComponents();
        cargarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puerta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_Mem = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Eli = new javax.swing.JTextField();
        txt_Mod = new javax.swing.JTextField();
        bt_Mod = new javax.swing.JButton();
        bt_Eli = new javax.swing.JButton();

        puerta.setBackground(new java.awt.Color(255, 255, 255));

        tab_Mem.setBackground(new java.awt.Color(255, 85, 30));
        tab_Mem.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        tab_Mem.setForeground(new java.awt.Color(255, 255, 255));
        tab_Mem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "DPI", "Cliente", "Tipo", "Fecha Inicio", "Fecha Fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab_Mem);

        jLabel1.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 85, 30));
        jLabel1.setText("Lista de Membresias");

        jLabel2.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 85, 30));
        jLabel2.setText("Modificar");

        jLabel3.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 85, 30));
        jLabel3.setText("Eliminar");

        txt_Eli.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        txt_Eli.setForeground(new java.awt.Color(0, 0, 0));
        txt_Eli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 85, 30)));

        txt_Mod.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        txt_Mod.setForeground(new java.awt.Color(0, 0, 0));
        txt_Mod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 85, 30)));

        bt_Mod.setBackground(new java.awt.Color(255, 85, 30));
        bt_Mod.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Mod.setForeground(new java.awt.Color(255, 255, 255));
        bt_Mod.setText("modificar");
        bt_Mod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ModActionPerformed(evt);
            }
        });

        bt_Eli.setBackground(new java.awt.Color(255, 85, 30));
        bt_Eli.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Eli.setForeground(new java.awt.Color(255, 255, 255));
        bt_Eli.setText("eliminar");
        bt_Eli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Eli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout puertaLayout = new javax.swing.GroupLayout(puerta);
        puerta.setLayout(puertaLayout);
        puertaLayout.setHorizontalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)
                            .addGroup(puertaLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(puertaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Eli, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(puertaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt_Mod, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt_Mod)
                            .addComponent(bt_Eli))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        puertaLayout.setVerticalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Eli, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Eli))
                .addGap(58, 58, 58)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Mod, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Mod))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_EliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EliActionPerformed
        // TODO add your handling code here:
        try {
            String sId = txt_Eli.getText();
            int id = Integer.parseInt(sId);
            int filas = dao.eliminar(id);
            
            if (filas > 0) {
                JOptionPane.showMessageDialog(this, "Membresia eliminada");
                txt_Eli.setText("");
                cargarLista();
            } else {
                JOptionPane.showMessageDialog(this, "No se encontro un empleado con ese DPI");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID debe ser numero");
        }
    }//GEN-LAST:event_bt_EliActionPerformed

    private void bt_ModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ModActionPerformed
        // TODO add your handling code here:
        try {
            String sId = txt_Mod.getText();
            int id = Integer.parseInt(sId);
            Membresia mem = dao.buscar(id);

            if (mem != null) {
                long dpi = mem.getDpi();
                int tipo = mem.getTipo();
                Date fechaInicio = mem.getFechaInicio();
                Date fechaFin = mem.getFechaFin();
                Utils.mostrarPanel(puerta, new ModMembresia(id, dpi));

            } else {
                JOptionPane.showMessageDialog(this, "No se encontro id de membresia");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El DPI debe ser un numero valido");
        }
    }//GEN-LAST:event_bt_ModActionPerformed
    public void cargarLista() {
        DefaultTableModel modelo = (DefaultTableModel) tab_Mem.getModel();
        modelo.setRowCount(0);
        List<MembresiaDetalle> lista = dao.listarMembresias();

        for (MembresiaDetalle m : lista) {
            modelo.addRow(new Object[]{
                m.getIdMembresia(),
                m.getDpi(),
                m.getCliente(),
                m.getTipoMembresia(),
                m.getFechaInicio(),
                m.getFechaFin()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Eli;
    private javax.swing.JButton bt_Mod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel puerta;
    private javax.swing.JTable tab_Mem;
    private javax.swing.JTextField txt_Eli;
    private javax.swing.JTextField txt_Mod;
    // End of variables declaration//GEN-END:variables
}
