package main.interfaz.empleado;

import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import main.dao.*;
import main.models.*;
import main.utils.Utils;
/**
 *
 * @author marco
 */
public class lista_Asistencias extends javax.swing.JPanel {

    /**
     * Creates new form lista_Asistencias
     */
    
    AsistenciaDao dao = new AsistenciaDao();
    
    public lista_Asistencias() {
        initComponents();
        JTableHeader header = tab_Asistencias.getTableHeader();
        header.setBackground(Color.MAGENTA);
        header.setForeground(Color.black);
        tab_Asistencias.setGridColor(Color.WHITE);
        tab_Asistencias.setShowVerticalLines(true);
        header.setFont(new Font("Free Mono", Font.BOLD, 15));
        cargarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_Asistencias = new javax.swing.JTable();
        bt_Eliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Lista de Asistencias");

        tab_Asistencias.setBackground(new java.awt.Color(204, 0, 204));
        tab_Asistencias.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        tab_Asistencias.setForeground(new java.awt.Color(255, 255, 255));
        tab_Asistencias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "DPI", "Nombre", "Sucursal", "Fecha-Hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab_Asistencias);
        if (tab_Asistencias.getColumnModel().getColumnCount() > 0) {
            tab_Asistencias.getColumnModel().getColumn(0).setMinWidth(80);
            tab_Asistencias.getColumnModel().getColumn(0).setMaxWidth(80);
            tab_Asistencias.getColumnModel().getColumn(3).setMinWidth(100);
            tab_Asistencias.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        bt_Eliminar.setBackground(new java.awt.Color(204, 0, 0));
        bt_Eliminar.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        bt_Eliminar.setText("eliminar");
        bt_Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EliminarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Acciones");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(bt_Eliminar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_Eliminar)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EliminarActionPerformed
        // TODO add your handling code here:
        String idStr = Utils.selecDatTable(tab_Asistencias, 0, "Seleccione el ID en la tabla");
        if (idStr != null) {
            int id = Integer.parseInt(idStr);
            dao.eliminar(id);
            JOptionPane.showMessageDialog(this, "Asistencia eliminada");
            cargarLista();
        } 
    }//GEN-LAST:event_bt_EliminarActionPerformed
    
    public void cargarLista() {
        DefaultTableModel modelo = (DefaultTableModel) tab_Asistencias.getModel();
        modelo.setRowCount(0);
        List<Asistencia> lista = dao.listar();

        for (Asistencia asi : lista) {
            modelo.addRow(new Object[]{
                asi.getId(),
                asi.getDpi_cliente(),
                Utils.nombreCliente(asi.getDpi_cliente()),
                Utils.getSucursalNombre(asi.getId_sucursal()),
                asi.getFecha_hora()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab_Asistencias;
    // End of variables declaration//GEN-END:variables
}
