package main.interfaz.empleado;

import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import main.dao.*;
import main.models.*;
import main.utils.Utils;

/**
 *
 * @author marco
 */
public class Lista_Pagos extends javax.swing.JPanel {

    /**
     * Creates new form Lista_Pagos
     */
    PagoDao dao = new PagoDao();
    AdicionalDao adiDao = new AdicionalDao();
    ClienteDao cliDao = new ClienteDao();

    public Lista_Pagos() {
        initComponents();
        JTableHeader header = tab_Pagos.getTableHeader();
        header.setBackground(Color.MAGENTA);
        header.setForeground(Color.black);
        tab_Pagos.setGridColor(Color.WHITE);
        tab_Pagos.setShowVerticalLines(true);
        header.setFont(new Font("Free Mono", Font.BOLD, 15));
        cargarLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puerta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_Pagos = new javax.swing.JTable();
        bt_Eliminar = new javax.swing.JButton();
        bt_Detalles = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        puerta.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 204));
        jLabel1.setText("Lista de Pagos");

        tab_Pagos.setBackground(new java.awt.Color(204, 0, 204));
        tab_Pagos.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        tab_Pagos.setForeground(new java.awt.Color(255, 255, 255));
        tab_Pagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "DPI", "Nombre", "Servicio", "Total", "Adicional"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab_Pagos);
        if (tab_Pagos.getColumnModel().getColumnCount() > 0) {
            tab_Pagos.getColumnModel().getColumn(0).setMinWidth(80);
            tab_Pagos.getColumnModel().getColumn(0).setPreferredWidth(80);
            tab_Pagos.getColumnModel().getColumn(0).setMaxWidth(80);
            tab_Pagos.getColumnModel().getColumn(1).setMinWidth(150);
            tab_Pagos.getColumnModel().getColumn(1).setPreferredWidth(150);
            tab_Pagos.getColumnModel().getColumn(1).setMaxWidth(150);
            tab_Pagos.getColumnModel().getColumn(3).setMinWidth(150);
            tab_Pagos.getColumnModel().getColumn(3).setPreferredWidth(150);
            tab_Pagos.getColumnModel().getColumn(3).setMaxWidth(150);
            tab_Pagos.getColumnModel().getColumn(4).setMinWidth(100);
            tab_Pagos.getColumnModel().getColumn(4).setPreferredWidth(100);
            tab_Pagos.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        bt_Eliminar.setBackground(new java.awt.Color(204, 0, 0));
        bt_Eliminar.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        bt_Eliminar.setText("eliminar");
        bt_Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EliminarActionPerformed(evt);
            }
        });

        bt_Detalles.setBackground(new java.awt.Color(0, 204, 204));
        bt_Detalles.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Detalles.setForeground(new java.awt.Color(0, 0, 0));
        bt_Detalles.setText("detalles");
        bt_Detalles.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Detalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_DetallesActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Acciones");

        javax.swing.GroupLayout puertaLayout = new javax.swing.GroupLayout(puerta);
        puerta.setLayout(puertaLayout);
        puertaLayout.setHorizontalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(puertaLayout.createSequentialGroup()
                                .addComponent(bt_Detalles)
                                .addGap(18, 18, 18)
                                .addComponent(bt_Eliminar)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        puertaLayout.setVerticalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Detalles)
                    .addComponent(bt_Eliminar))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EliminarActionPerformed
        // TODO add your handling code here:
        String idStr = Utils.selecDatTable(tab_Pagos, 0, "Seleccione el ID en la tabla");
        if (idStr != null) {
            int id = Integer.parseInt(idStr);
            dao.eliminar(id);
            JOptionPane.showMessageDialog(this, "Pago eliminada");
            cargarLista();
        }
    }//GEN-LAST:event_bt_EliminarActionPerformed

    private void bt_DetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_DetallesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bt_DetallesActionPerformed

    public void cargarLista() {
        DefaultTableModel modelo = (DefaultTableModel) tab_Pagos.getModel();
        modelo.setRowCount(0);
        List<Pago> lista = dao.listar();
        
        for (Pago pago : lista) {
            modelo.addRow(new Object[]{
                pago.getId(),
                pago.getDpi(),
                nombreCliente(pago.getDpi()),
                pago.getTipo(),
                pago.getMonto(),
                nombreAdicional(pago.getId_adicional()),
            });
        }
    }
    
    public String nombreAdicional(int id) {
        Adicional adi = adiDao.buscar(id);
        if (adi != null) {
            String nombre = adi.getNombre();
            return nombre;
        } else {
            return "    ------";
        }
    }
    
    public String nombreCliente(long dpi) {
        Cliente cli = cliDao.buscar(dpi);
        if (cli != null) {
            String nombre = cli.getNombre();
            String apellido = cli.getApellido();
            return nombre + " " + apellido;
        } else {
            return "Desconocido";
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Detalles;
    private javax.swing.JButton bt_Eliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel puerta;
    private javax.swing.JTable tab_Pagos;
    // End of variables declaration//GEN-END:variables
}
