package main.interfaz.empleado;

import java.sql.Date;
import javax.swing.JOptionPane;
import main.dao.MembresiasDao;
import main.models.Membresia;
import main.utils.Utils;

/**
 *
 * @author marco
 */
public class ModMembresia extends javax.swing.JPanel {

    /**
     * Creates new form ModMembresia
     */
    public ModMembresia(int id, long dpi, int tipo, Date fechaInicio, Date fechaFin) {
        initComponents();
        String sid = Integer.toString(id);
        String sdpi = String.valueOf(dpi);
        String stipo = Utils.getIdTipo(tipo);
        String sfechaInicio = fechaInicio.toString();
        String sfechaFin = fechaFin.toString();
        txt_ID.setText(sid);
        txt_DPI.setText(sdpi);
        com_Tipo.setSelectedItem(stipo);
        txt_FechaInicio.setText(sfechaInicio);
        txt_FechaFin.setText(sfechaFin);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puerta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_ID = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_DPI = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        com_Tipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_FechaInicio = new javax.swing.JTextField();
        txt_FechaFin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        bt_Mod = new javax.swing.JButton();
        bt_Cancelar = new javax.swing.JButton();

        puerta.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 85, 30));
        jLabel1.setText("Modificar Membresia");

        jLabel2.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 85, 30));
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 85, 30));
        jLabel3.setText("Tipo");

        txt_ID.setEditable(false);
        txt_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 85, 30)));
        txt_ID.setFont(new java.awt.Font("FreeMono", 1, 20)); // NOI18N
        txt_ID.setForeground(new java.awt.Color(0, 0, 0));
        txt_ID.setFocusable(false);
        jScrollPane1.setViewportView(txt_ID);

        txt_DPI.setEditable(false);
        txt_DPI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 85, 30)));
        txt_DPI.setFont(new java.awt.Font("FreeMono", 1, 20)); // NOI18N
        txt_DPI.setForeground(new java.awt.Color(0, 0, 0));
        txt_DPI.setFocusable(false);
        jScrollPane2.setViewportView(txt_DPI);

        jLabel4.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 85, 30));
        jLabel4.setText("DPI");

        com_Tipo.setBackground(new java.awt.Color(255, 85, 30));
        com_Tipo.setForeground(new java.awt.Color(255, 255, 255));
        com_Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basica", "Premiun", "VIP" }));

        jLabel5.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 85, 30));
        jLabel5.setText("Fecha Fin");

        jLabel6.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 85, 30));
        jLabel6.setText("Fecha Inicio");

        txt_FechaInicio.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        txt_FechaInicio.setForeground(new java.awt.Color(0, 0, 0));
        txt_FechaInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 85, 30)));

        txt_FechaFin.setFont(new java.awt.Font("FreeMono", 1, 14)); // NOI18N
        txt_FechaFin.setForeground(new java.awt.Color(0, 0, 0));
        txt_FechaFin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 85, 30)));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/membresia.png"))); // NOI18N

        bt_Mod.setBackground(new java.awt.Color(255, 85, 30));
        bt_Mod.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Mod.setForeground(new java.awt.Color(255, 255, 255));
        bt_Mod.setText("modificar");
        bt_Mod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ModActionPerformed(evt);
            }
        });

        bt_Cancelar.setBackground(new java.awt.Color(204, 0, 0));
        bt_Cancelar.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        bt_Cancelar.setText("cancelar");
        bt_Cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout puertaLayout = new javax.swing.GroupLayout(puerta);
        puerta.setLayout(puertaLayout);
        puertaLayout.setHorizontalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, puertaLayout.createSequentialGroup()
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, puertaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, puertaLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(puertaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(puertaLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(170, 170, 170)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 194, Short.MAX_VALUE))
                                    .addGroup(puertaLayout.createSequentialGroup()
                                        .addComponent(com_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7))))
                            .addGroup(puertaLayout.createSequentialGroup()
                                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(puertaLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_FechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(puertaLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_FechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(112, 112, 112))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, puertaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_Cancelar)
                .addGap(59, 59, 59)
                .addComponent(bt_Mod)
                .addGap(91, 91, 91))
        );
        puertaLayout.setVerticalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(com_Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_FechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(txt_FechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Mod)
                    .addComponent(bt_Cancelar))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ModActionPerformed
        // TODO add your handling code here:
        try {
            long dpi = Long.parseLong(txt_DPI.getText());
            String tipo = (String) com_Tipo.getSelectedItem();
            String fecha_Inicio = txt_FechaInicio.getText();
            String fecha_Fin = txt_FechaFin.getText();

            int idTipo = Utils.obtenerIdTipo(tipo);

            java.sql.Date fechaInicioSQL = java.sql.Date.valueOf(fecha_Inicio);
            java.sql.Date fechaFinSQL = java.sql.Date.valueOf(fecha_Fin);

            System.out.println(dpi + " " + idTipo + " " + fechaInicioSQL + " " + fechaFinSQL);
            Membresia mem = new Membresia(dpi, idTipo, fechaInicioSQL, fechaFinSQL);
            MembresiasDao dao = new MembresiasDao();
            dao.actualizar(mem);
            JOptionPane.showMessageDialog(this, "Membresia Modificada");
            Utils.mostrarPanel(puerta, new Lista_Membresias());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El DPI debe ser un numero valido");
        }
    }//GEN-LAST:event_bt_ModActionPerformed

    private void bt_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelarActionPerformed
        // TODO add your handling code here:
        Utils.mostrarPanel(puerta, new Lista_Membresias());
    }//GEN-LAST:event_bt_CancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Cancelar;
    private javax.swing.JButton bt_Mod;
    private javax.swing.JComboBox<String> com_Tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel puerta;
    private javax.swing.JTextPane txt_DPI;
    private javax.swing.JTextField txt_FechaFin;
    private javax.swing.JTextField txt_FechaInicio;
    private javax.swing.JTextPane txt_ID;
    // End of variables declaration//GEN-END:variables
}
