package main.interfaz.empleado;

import main.interfaz.LoginEmpleado;
import main.utils.Utils;

/**
 *
 * @author marco
 */
public class Perfil extends javax.swing.JPanel {

    /**
     * Creates new form Perfil
     */
    
    String login;
    int idRol;
    public Perfil(String dpi, String nombre, String apellido, String telefono,
            String direccion, String sucursal, String rol) {
        initComponents();
        txt_DPI.setText(dpi);
        txt_Nombre.setText(nombre);
        txt_Apellido.setText(apellido);
        txt_Telefono.setText(telefono);
        txt_Direccion.setText(direccion);
        txt_Sucursal.setText(sucursal);
        txt_Rol.setText(rol);
        String imgRol = Utils.imagenRol(rol);
        IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/" + imgRol)));
        idRol = Utils.obtenerIdRol(rol);
        login = Utils.loginRol(rol);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puerta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IMG = new javax.swing.JLabel();
        bt_Cerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Nombre = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_DPI = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_Apellido = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_Telefono = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        txt_Direccion = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        txt_Rol = new javax.swing.JTextPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        txt_Sucursal = new javax.swing.JTextPane();

        puerta.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 85, 30));
        jLabel1.setText("Perfil");

        jLabel2.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 85, 30));
        jLabel2.setText("DPI");

        jLabel3.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 85, 30));
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 85, 30));
        jLabel4.setText("Apellido");

        jLabel5.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 85, 30));
        jLabel5.setText("Telefono");

        jLabel6.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 85, 30));
        jLabel6.setText("Rol");

        jLabel7.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 85, 30));
        jLabel7.setText("Direccion");

        jLabel8.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 85, 30));
        jLabel8.setText("Sucursal");

        IMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/service.png"))); // NOI18N

        bt_Cerrar.setBackground(new java.awt.Color(204, 0, 0));
        bt_Cerrar.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Cerrar.setForeground(new java.awt.Color(255, 255, 255));
        bt_Cerrar.setText("cerrar sesion");
        bt_Cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CerrarActionPerformed(evt);
            }
        });

        txt_Nombre.setEditable(false);
        txt_Nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 85, 30)));
        txt_Nombre.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        txt_Nombre.setForeground(new java.awt.Color(0, 0, 0));
        txt_Nombre.setFocusable(false);
        jScrollPane1.setViewportView(txt_Nombre);

        txt_DPI.setEditable(false);
        txt_DPI.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 85, 30)));
        txt_DPI.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        txt_DPI.setForeground(new java.awt.Color(0, 0, 0));
        txt_DPI.setFocusable(false);
        jScrollPane2.setViewportView(txt_DPI);

        txt_Apellido.setEditable(false);
        txt_Apellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 85, 30)));
        txt_Apellido.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        txt_Apellido.setForeground(new java.awt.Color(0, 0, 0));
        txt_Apellido.setFocusable(false);
        jScrollPane3.setViewportView(txt_Apellido);

        txt_Telefono.setEditable(false);
        txt_Telefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 85, 30)));
        txt_Telefono.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        txt_Telefono.setForeground(new java.awt.Color(0, 0, 0));
        txt_Telefono.setFocusable(false);
        jScrollPane4.setViewportView(txt_Telefono);

        txt_Direccion.setEditable(false);
        txt_Direccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 85, 30)));
        txt_Direccion.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        txt_Direccion.setForeground(new java.awt.Color(0, 0, 0));
        txt_Direccion.setFocusable(false);
        jScrollPane5.setViewportView(txt_Direccion);

        txt_Rol.setEditable(false);
        txt_Rol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 85, 30)));
        txt_Rol.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        txt_Rol.setForeground(new java.awt.Color(0, 0, 0));
        txt_Rol.setFocusable(false);
        jScrollPane6.setViewportView(txt_Rol);

        txt_Sucursal.setEditable(false);
        txt_Sucursal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 85, 30)));
        txt_Sucursal.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        txt_Sucursal.setForeground(new java.awt.Color(0, 0, 0));
        txt_Sucursal.setFocusable(false);
        jScrollPane7.setViewportView(txt_Sucursal);

        javax.swing.GroupLayout puertaLayout = new javax.swing.GroupLayout(puerta);
        puerta.setLayout(puertaLayout);
        puertaLayout.setHorizontalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(puertaLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(puertaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(puertaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 104, Short.MAX_VALUE)
                        .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, puertaLayout.createSequentialGroup()
                                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, puertaLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(puertaLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(80, 80, 80))
                            .addGroup(puertaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IMG)
                        .addGap(129, 129, 129))))
            .addGroup(puertaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_Cerrar)
                .addGap(25, 25, 25))
        );
        puertaLayout.setVerticalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(bt_Cerrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, puertaLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, puertaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IMG)
                        .addGap(40, 40, 40))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CerrarActionPerformed
        // TODO add your handling code here:
        Utils.cambiarPanel(this, new LoginEmpleado(login, idRol));
    }//GEN-LAST:event_bt_CerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMG;
    private javax.swing.JButton bt_Cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel puerta;
    private javax.swing.JTextPane txt_Apellido;
    private javax.swing.JTextPane txt_DPI;
    private javax.swing.JTextPane txt_Direccion;
    private javax.swing.JTextPane txt_Nombre;
    private javax.swing.JTextPane txt_Rol;
    private javax.swing.JTextPane txt_Sucursal;
    private javax.swing.JTextPane txt_Telefono;
    // End of variables declaration//GEN-END:variables
}
