package main.interfaz.empleado;

import java.awt.Color;
import javax.swing.JOptionPane;
import main.dao.EmpleadoDao;
import main.interfaz.Roles;
import main.models.Empleado;
import main.utils.Utils;

/**
 *
 * @author marco
 */
public class Recepcionista extends javax.swing.JPanel {

    /**
     * Creates new form Recepcionista
     */
    EmpleadoDao dao = new EmpleadoDao();

    public Recepcionista(String user) {
        initComponents();
        txtUser.setText("");
        txtUser.setText(user);
        Utils.mostrarPanel(puerta, new CrearCliente());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        barra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUser = new javax.swing.JLabel();
        bt_ListaClientes = new javax.swing.JLabel();
        bt_CrearCliente = new javax.swing.JLabel();
        bt_Pagos = new javax.swing.JLabel();
        bt_membresias = new javax.swing.JLabel();
        puerta = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra.setBackground(new java.awt.Color(204, 0, 204));
        barra.setPreferredSize(new java.awt.Dimension(1000, 130));
        barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Recepcionista");
        barra.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 37, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gym1.png"))); // NOI18N
        barra.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 6, -1, -1));

        txtUser.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtUser.setText("Usuario");
        txtUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtUserMouseExited(evt);
            }
        });
        barra.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 82, -1, -1));

        bt_ListaClientes.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_ListaClientes.setForeground(new java.awt.Color(255, 255, 255));
        bt_ListaClientes.setText("Lista Clientes");
        bt_ListaClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_ListaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_ListaClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_ListaClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_ListaClientesMouseExited(evt);
            }
        });
        barra.add(bt_ListaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, -1, -1));

        bt_CrearCliente.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_CrearCliente.setForeground(new java.awt.Color(255, 255, 255));
        bt_CrearCliente.setText("Crear Cliente");
        bt_CrearCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_CrearCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_CrearClienteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_CrearClienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_CrearClienteMouseExited(evt);
            }
        });
        barra.add(bt_CrearCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        bt_Pagos.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Pagos.setForeground(new java.awt.Color(255, 255, 255));
        bt_Pagos.setText("Pagos");
        bt_Pagos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Pagos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_PagosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_PagosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_PagosMouseExited(evt);
            }
        });
        barra.add(bt_Pagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, 20));

        bt_membresias.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_membresias.setForeground(new java.awt.Color(255, 255, 255));
        bt_membresias.setText("Membresias");
        bt_membresias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_membresias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_membresiasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bt_membresiasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bt_membresiasMouseExited(evt);
            }
        });
        barra.add(bt_membresias, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, -1, -1));

        jPanel1.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 130));

        puerta.setBackground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout puertaLayout = new javax.swing.GroupLayout(puerta);
        puerta.setLayout(puertaLayout);
        puertaLayout.setHorizontalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        puertaLayout.setVerticalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        jPanel1.add(puerta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1000, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_CrearClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CrearClienteMouseClicked
        // TODO add your handling code here:
        Utils.mostrarPanel(puerta, new CrearCliente());
    }//GEN-LAST:event_bt_CrearClienteMouseClicked

    private void bt_CrearClienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CrearClienteMouseEntered
        // TODO add your handling code here:
        bt_CrearCliente.setForeground(new Color(242, 140, 40));
    }//GEN-LAST:event_bt_CrearClienteMouseEntered

    private void bt_CrearClienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_CrearClienteMouseExited
        // TODO add your handling code here:
        bt_CrearCliente.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_bt_CrearClienteMouseExited

    private void bt_ListaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ListaClientesMouseClicked
        // TODO add your handling code here:
        Utils.mostrarPanel(puerta, new ListaClientes());
    }//GEN-LAST:event_bt_ListaClientesMouseClicked

    private void bt_ListaClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ListaClientesMouseEntered
        // TODO add your handling code here:
        bt_ListaClientes.setForeground(new Color(242, 140, 40));
    }//GEN-LAST:event_bt_ListaClientesMouseEntered

    private void bt_ListaClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ListaClientesMouseExited
        // TODO add your handling code here:
        bt_ListaClientes.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_bt_ListaClientesMouseExited

    private void bt_PagosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_PagosMouseClicked
        // TODO add your handling code here:
        Utils.mostrarPanel(puerta, new Pagos());
    }//GEN-LAST:event_bt_PagosMouseClicked

    private void bt_PagosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_PagosMouseEntered
        // TODO add your handling code here:
        bt_Pagos.setForeground(new Color(242, 140, 40));
    }//GEN-LAST:event_bt_PagosMouseEntered

    private void bt_PagosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_PagosMouseExited
        // TODO add your handling code here:
        bt_Pagos.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_bt_PagosMouseExited

    private void txtUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseClicked
        // TODO add your handling code here:
        String usuario = txtUser.getText();
        Empleado emp = dao.perfil(usuario);

        if (emp != null) {
            long dpi = emp.getDpi();
            String nombre = emp.getNombre();
            String apellido = emp.getApellido();
            String telefono = emp.getTelefono();
            String direccion = emp.getDireccion();
            int sucursal = emp.getIdSucursal();
            int rol = emp.getIdRol();
            
            String sdpi = String.valueOf(dpi);
            String sSucursal = Utils.getSucursalNombre(sucursal);
            String sRol = Utils.getRolNombre(rol);
            
            Utils.mostrarPanel(puerta, new Perfil(sdpi, nombre, apellido, telefono, direccion, sSucursal, sRol));

        } else {
            JOptionPane.showMessageDialog(this, "Error de Usuario");
            Utils.cambiarPanel(puerta, new Roles());
        }
    }//GEN-LAST:event_txtUserMouseClicked

    private void txtUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseEntered
        // TODO add your handling code here:
        txtUser.setForeground(new Color(242, 140, 40));
    }//GEN-LAST:event_txtUserMouseEntered

    private void txtUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserMouseExited
        // TODO add your handling code here:
        txtUser.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_txtUserMouseExited

    private void bt_membresiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_membresiasMouseClicked
        // TODO add your handling code here:
        Utils.mostrarPanel(puerta, new Lista_Membresias());
    }//GEN-LAST:event_bt_membresiasMouseClicked

    private void bt_membresiasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_membresiasMouseEntered
        // TODO add your handling code here:
        bt_membresias.setForeground(new Color(242, 140, 40));
    }//GEN-LAST:event_bt_membresiasMouseEntered

    private void bt_membresiasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_membresiasMouseExited
        // TODO add your handling code here:
        bt_membresias.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_bt_membresiasMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barra;
    private javax.swing.JLabel bt_CrearCliente;
    private javax.swing.JLabel bt_ListaClientes;
    private javax.swing.JLabel bt_Pagos;
    private javax.swing.JLabel bt_membresias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel puerta;
    private javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables
}
