package main.interfaz.empleado.entrenador;

import java.util.List;
import javax.swing.JOptionPane;
import main.dao.*;
import main.models.*;
import main.utils.Utils;

/**
 *
 * @author marco
 */
public class Ejercicios extends javax.swing.JPanel {

    /**
     * Creates new form Ejercicio
     */
    RutinaDao rutDao = new RutinaDao();
    EjercicioDao ejeDao = new EjercicioDao();
    Rutina_EjercicioDao rutEjeDao = new Rutina_EjercicioDao();
    
    private long dpi_entrenador;
  
    public Ejercicios(String idStr, long dpi) {
        initComponents();
        txt_ID.setText(idStr);
        int id = Integer.parseInt(idStr);
        txt_Nombre.setText(nombreCliente(id));
        cargarEjercicios();
        dpi_entrenador = dpi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puerta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_ID = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Nombre = new javax.swing.JTextPane();
        com_Ejercicio = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_Orden = new javax.swing.JTextPane();
        bt_Crear = new javax.swing.JButton();
        bt_Cancelar = new javax.swing.JButton();

        puerta.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("Ejercicios");

        jLabel2.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ID");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        jScrollPane1.setForeground(new java.awt.Color(0, 0, 0));

        txt_ID.setEditable(false);
        txt_ID.setBackground(new java.awt.Color(255, 255, 255));
        txt_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        txt_ID.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        txt_ID.setForeground(new java.awt.Color(0, 0, 0));
        txt_ID.setFocusable(false);
        jScrollPane1.setViewportView(txt_ID);

        jLabel3.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        jScrollPane2.setForeground(new java.awt.Color(0, 0, 0));

        txt_Nombre.setEditable(false);
        txt_Nombre.setBackground(new java.awt.Color(255, 255, 255));
        txt_Nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        txt_Nombre.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        txt_Nombre.setForeground(new java.awt.Color(0, 0, 0));
        txt_Nombre.setFocusable(false);
        jScrollPane2.setViewportView(txt_Nombre);

        com_Ejercicio.setBackground(new java.awt.Color(51, 153, 0));
        com_Ejercicio.setFont(new java.awt.Font("FreeMono", 1, 20)); // NOI18N
        com_Ejercicio.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Ejercicio");

        jLabel5.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Orden");

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        jScrollPane3.setForeground(new java.awt.Color(0, 0, 0));

        txt_Orden.setBackground(new java.awt.Color(255, 255, 255));
        txt_Orden.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 0)));
        txt_Orden.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        txt_Orden.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane3.setViewportView(txt_Orden);

        bt_Crear.setBackground(new java.awt.Color(0, 204, 0));
        bt_Crear.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Crear.setForeground(new java.awt.Color(0, 0, 0));
        bt_Crear.setText("crear");
        bt_Crear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CrearActionPerformed(evt);
            }
        });

        bt_Cancelar.setBackground(new java.awt.Color(204, 0, 0));
        bt_Cancelar.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        bt_Cancelar.setText("cancelar");
        bt_Cancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout puertaLayout = new javax.swing.GroupLayout(puerta);
        puerta.setLayout(puertaLayout);
        puertaLayout.setHorizontalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(puertaLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(com_Ejercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, puertaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_Cancelar)
                .addGap(18, 18, 18)
                .addComponent(bt_Crear)
                .addGap(55, 55, 55))
        );
        puertaLayout.setVerticalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(com_Ejercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Crear)
                    .addComponent(bt_Cancelar))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CrearActionPerformed
        // TODO add your handling code here:
        String idStr = txt_ID.getText();
        int id_rutina = Integer.parseInt(idStr);
        String ordenStr = txt_Orden.getText();
        int orden = Integer.parseInt(ordenStr);
        
        Ejercicio selec = (Ejercicio) com_Ejercicio.getSelectedItem();
        if (selec == null) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un ejercicio");
            return;
        }
        int id_ejercicio = selec.getId_ejercicio();
        
        Rutina_Ejercicio rutEje = new Rutina_Ejercicio(id_rutina, id_ejercicio, orden);
        rutEjeDao.crear(rutEje);
        JOptionPane.showMessageDialog(this, "Ejercicio creado");
        Utils.mostrarPanel(puerta, new lista_Rutinas(dpi_entrenador));
    }//GEN-LAST:event_bt_CrearActionPerformed

    private void bt_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelarActionPerformed
        // TODO add your handling code here:
        Utils.mostrarPanel(puerta, new lista_Rutinas(dpi_entrenador));
    }//GEN-LAST:event_bt_CancelarActionPerformed

    private String nombreCliente(int id) {
        Rutina rut = rutDao.buscar(id);
        if (rut != null) {
            String nombre = Utils.nombreCliente(rut.getDpi_cliente());
            return nombre;
        } else {
            return "Desconocido";
        }
    }

    private void cargarEjercicios() {
        com_Ejercicio.removeAllItems();
        List<Ejercicio> lista = ejeDao.listar();

        for (Ejercicio eje : lista) {
            com_Ejercicio.addItem(eje);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Cancelar;
    private javax.swing.JButton bt_Crear;
    private javax.swing.JComboBox<Ejercicio> com_Ejercicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel puerta;
    private javax.swing.JTextPane txt_ID;
    private javax.swing.JTextPane txt_Nombre;
    private javax.swing.JTextPane txt_Orden;
    // End of variables declaration//GEN-END:variables
}
