package main.interfaz.empleado.entrenador;

import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import main.dao.*;
import main.models.*;
import main.utils.Utils;

/**
 *
 * @author marco
 */
public class lista_Clientes extends javax.swing.JPanel {

    /**
     * Creates new form lista_Clientes
     */
    
    Entrenador_ClienteDao enciDao = new Entrenador_ClienteDao();
    ClienteDao cliDao = new ClienteDao();
    
    private long dpiE; 
    public lista_Clientes(long dpi) {
        initComponents();
        cargarLista(dpi);
        dpiE = dpi;
        JTableHeader header = tab_Clientes.getTableHeader();
        header.setBackground(Color.GREEN);
        header.setForeground(Color.black);
        header.setFont(new Font("Free Mono", Font.BOLD, 15));
        tab_Clientes.setGridColor(Color.WHITE);
        tab_Clientes.setShowVerticalLines(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puerta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_Clientes = new javax.swing.JTable();
        bt_Rutina = new javax.swing.JButton();

        puerta.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("Lista de Clientes");

        tab_Clientes.setBackground(new java.awt.Color(51, 153, 0));
        tab_Clientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tab_Clientes.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        tab_Clientes.setForeground(new java.awt.Color(0, 0, 0));
        tab_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "DPI", "Nombre", "Fecha Asignacion", "Fecha Fin"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab_Clientes);
        if (tab_Clientes.getColumnModel().getColumnCount() > 0) {
            tab_Clientes.getColumnModel().getColumn(0).setMinWidth(80);
            tab_Clientes.getColumnModel().getColumn(0).setPreferredWidth(80);
            tab_Clientes.getColumnModel().getColumn(0).setMaxWidth(80);
            tab_Clientes.getColumnModel().getColumn(3).setMinWidth(150);
            tab_Clientes.getColumnModel().getColumn(3).setPreferredWidth(150);
            tab_Clientes.getColumnModel().getColumn(3).setMaxWidth(150);
            tab_Clientes.getColumnModel().getColumn(4).setMinWidth(150);
            tab_Clientes.getColumnModel().getColumn(4).setPreferredWidth(100);
            tab_Clientes.getColumnModel().getColumn(4).setMaxWidth(150);
        }

        bt_Rutina.setBackground(new java.awt.Color(0, 153, 0));
        bt_Rutina.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Rutina.setForeground(new java.awt.Color(0, 0, 0));
        bt_Rutina.setText("rutina");
        bt_Rutina.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Rutina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_RutinaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout puertaLayout = new javax.swing.GroupLayout(puerta);
        puerta.setLayout(puertaLayout);
        puertaLayout.setHorizontalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(puertaLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(bt_Rutina)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        puertaLayout.setVerticalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(bt_Rutina)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_RutinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_RutinaActionPerformed
        // TODO add your handling code here:
        String dpiStr = Utils.selecDatTable(tab_Clientes, 1, "Seleccione un cliente en la tabla");
        if (dpiStr != null) {
            long dpiC = Long.parseLong(dpiStr);
            Utils.mostrarPanel(puerta, new Rutinas(dpiE, dpiC));
        }
    }//GEN-LAST:event_bt_RutinaActionPerformed
    
    public void cargarLista(long dpi) {
        DefaultTableModel modelo = (DefaultTableModel) tab_Clientes.getModel();
        modelo.setRowCount(0);
        List<Entrenador_Cliente> lista = enciDao.listarPorEntrenador(dpi);
        
        for (Entrenador_Cliente enCi : lista) {
            modelo.addRow(new Object[] {
                enCi.getAsignacion(),
                enCi.getDpi_cliente(),
                Utils.nombreCliente(enCi.getDpi_cliente()),
                enCi.getFechaAsignacion(),
                enCi.getFechaFin()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Rutina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel puerta;
    private javax.swing.JTable tab_Clientes;
    // End of variables declaration//GEN-END:variables
}
