package main.interfaz.empleado.entrenador;

import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import main.dao.*;
import main.models.*;
import main.utils.Utils;

/**
 *
 * @author marco
 */
public class lista_Ejercicios extends javax.swing.JPanel {

    /**
     * Creates new form lista_Ejercicios
     */
    Rutina_EjercicioDao rutEjeDao = new Rutina_EjercicioDao();
    
    private long dpi_entrenador;
    
    public lista_Ejercicios(long dpi) {
        initComponents();
        JTableHeader header = tab_Ejercicios.getTableHeader();
        header.setBackground(Color.GREEN);
        header.setForeground(Color.black);
        tab_Ejercicios.setGridColor(Color.WHITE);
        tab_Ejercicios.setShowVerticalLines(true);
        header.setFont(new Font("Free Mono", Font.BOLD, 15));
        cargarLista(dpi);
        dpi_entrenador = dpi;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puerta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_Ejercicios = new javax.swing.JTable();

        puerta.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("Rutinas y Ejercicios");

        tab_Ejercicios.setBackground(new java.awt.Color(51, 153, 0));
        tab_Ejercicios.setFont(new java.awt.Font("FreeMono", 1, 16)); // NOI18N
        tab_Ejercicios.setForeground(new java.awt.Color(0, 0, 0));
        tab_Ejercicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "DPI", "Rutina", "Tipo", "Ejercicio", "Orden", "Fecha Inicio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab_Ejercicios);
        if (tab_Ejercicios.getColumnModel().getColumnCount() > 0) {
            tab_Ejercicios.getColumnModel().getColumn(0).setMinWidth(60);
            tab_Ejercicios.getColumnModel().getColumn(0).setMaxWidth(60);
            tab_Ejercicios.getColumnModel().getColumn(3).setMinWidth(70);
            tab_Ejercicios.getColumnModel().getColumn(3).setPreferredWidth(70);
            tab_Ejercicios.getColumnModel().getColumn(3).setMaxWidth(70);
            tab_Ejercicios.getColumnModel().getColumn(5).setMinWidth(60);
            tab_Ejercicios.getColumnModel().getColumn(5).setPreferredWidth(60);
            tab_Ejercicios.getColumnModel().getColumn(5).setMaxWidth(60);
            tab_Ejercicios.getColumnModel().getColumn(6).setMinWidth(130);
            tab_Ejercicios.getColumnModel().getColumn(6).setPreferredWidth(130);
            tab_Ejercicios.getColumnModel().getColumn(6).setMaxWidth(130);
        }

        javax.swing.GroupLayout puertaLayout = new javax.swing.GroupLayout(puerta);
        puerta.setLayout(puertaLayout);
        puertaLayout.setHorizontalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 988, Short.MAX_VALUE))
                .addContainerGap())
        );
        puertaLayout.setVerticalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void cargarLista(long dpi_entrenador) {
        DefaultTableModel modelo = (DefaultTableModel) tab_Ejercicios.getModel();
        modelo.setRowCount(0);

        List<VistaRutinaEjercicio> lista = rutEjeDao.listarVistaPorEntrenador(dpi_entrenador);

        for (VistaRutinaEjercicio v : lista) {
            modelo.addRow(new Object[]{
                v.getIdRutEje(),
                Utils.nombreCliente(v.getDpiCliente()),
                v.getNombreRutina(),
                v.getTipo(),
                v.getNombreEjercicio(),
                v.getOrden(),
                v.getFechaInicio()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel puerta;
    private javax.swing.JTable tab_Ejercicios;
    // End of variables declaration//GEN-END:variables
}
