package main.interfaz.empleado.entrenador;

import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import main.dao.RutinaDao;
import main.models.Rutina;
import main.utils.Utils;

/**
 *
 * @author marco
 */
public class lista_Rutinas extends javax.swing.JPanel {

    /**
     * Creates new form lista_Rutinas
     */
    
    RutinaDao rutDao = new RutinaDao();
    
    public lista_Rutinas(long dpi) {
        initComponents();
        JTableHeader header = tab_Rutinas.getTableHeader();
        header.setBackground(Color.GREEN);
        header.setForeground(Color.black);
        tab_Rutinas.setGridColor(Color.WHITE);
        tab_Rutinas.setShowVerticalLines(true);
        header.setFont(new Font("Free Mono", Font.BOLD, 15));
        cargarLista(dpi);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_Rutinas = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 0));
        jLabel1.setText("Lista de Rutinas");

        tab_Rutinas.setBackground(new java.awt.Color(51, 153, 0));
        tab_Rutinas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tab_Rutinas.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        tab_Rutinas.setForeground(new java.awt.Color(0, 0, 0));
        tab_Rutinas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "DPI", "Nombre", "Rutina", "Tipo", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab_Rutinas);
        if (tab_Rutinas.getColumnModel().getColumnCount() > 0) {
            tab_Rutinas.getColumnModel().getColumn(0).setMinWidth(80);
            tab_Rutinas.getColumnModel().getColumn(0).setPreferredWidth(80);
            tab_Rutinas.getColumnModel().getColumn(0).setMaxWidth(80);
            tab_Rutinas.getColumnModel().getColumn(4).setMinWidth(80);
            tab_Rutinas.getColumnModel().getColumn(4).setPreferredWidth(80);
            tab_Rutinas.getColumnModel().getColumn(4).setMaxWidth(80);
            tab_Rutinas.getColumnModel().getColumn(5).setMinWidth(150);
            tab_Rutinas.getColumnModel().getColumn(5).setPreferredWidth(150);
            tab_Rutinas.getColumnModel().getColumn(5).setMaxWidth(150);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 967, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void cargarLista(long dpi) {
        DefaultTableModel modelo = (DefaultTableModel) tab_Rutinas.getModel();
        modelo.setRowCount(0);
        List<Rutina> lista = rutDao.listarPorEntrenador(dpi);
        
        for (Rutina rut : lista) {
            modelo.addRow(new Object[] {
                rut.getId(),
                rut.getDpi_cliente(),
                Utils.nombreCliente(rut.getDpi_cliente()),
                rut.getNombre(),
                rut.getTipo(),
                rut.getFechaInicio()
            });
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab_Rutinas;
    // End of variables declaration//GEN-END:variables
}
