package main.interfaz.empleado.pagos;

import javax.swing.JOptionPane;
import main.dao.PagoDao;
import main.models.Pago;
import main.dao.MembresiasDao;
import main.models.Membresia;
import main.utils.Utils;

/**
 *
 * @author marco
 */
public class Servicio extends javax.swing.JPanel {

    /**
     * Creates new form Servicio
     */
    long dpi;
    String tipo;
    
    PagoDao dao = new PagoDao();

    public Servicio(long sdpi, String stipo) {
        initComponents();
        dpi = sdpi;
        tipo = stipo;
        txt_Descripcion.setText("Servicio de Membresia: " + membresia());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puerta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Monto = new javax.swing.JTextField();
        txt_FechaInicio = new javax.swing.JTextField();
        txt_FechaFin = new javax.swing.JTextField();
        bt_Pagar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Descripcion = new javax.swing.JTextPane();

        puerta.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Descripcion");

        jLabel2.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Monto");

        jLabel3.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha Fin");

        jLabel4.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Fecha Inicio");

        txt_Monto.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        txt_Monto.setForeground(new java.awt.Color(0, 0, 0));
        txt_Monto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204)));

        txt_FechaInicio.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        txt_FechaInicio.setForeground(new java.awt.Color(0, 0, 0));
        txt_FechaInicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204)));

        txt_FechaFin.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        txt_FechaFin.setForeground(new java.awt.Color(0, 0, 0));
        txt_FechaFin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204)));

        bt_Pagar.setBackground(new java.awt.Color(0, 0, 204));
        bt_Pagar.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Pagar.setForeground(new java.awt.Color(255, 255, 255));
        bt_Pagar.setText("pagar");
        bt_Pagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Pagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_PagarActionPerformed(evt);
            }
        });

        txt_Descripcion.setEditable(false);
        txt_Descripcion.setBackground(new java.awt.Color(255, 255, 255));
        txt_Descripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 204)));
        txt_Descripcion.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        txt_Descripcion.setForeground(new java.awt.Color(0, 0, 0));
        txt_Descripcion.setFocusable(false);
        jScrollPane2.setViewportView(txt_Descripcion);

        javax.swing.GroupLayout puertaLayout = new javax.swing.GroupLayout(puerta);
        puerta.setLayout(puertaLayout);
        puertaLayout.setHorizontalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, puertaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_Pagar)
                .addGap(49, 49, 49))
            .addGroup(puertaLayout.createSequentialGroup()
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Monto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(puertaLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(puertaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txt_FechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txt_FechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        puertaLayout.setVerticalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Monto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_FechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_FechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(bt_Pagar)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_PagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_PagarActionPerformed
        // TODO add your handling code here:
        String descripcion = txt_Descripcion.getText();
        double monton = Double.parseDouble(txt_Monto.getText().trim());
        String fecha_Inicio = txt_FechaInicio.getText().trim();
        String fecha_Fin = txt_FechaFin.getText().trim();

        if (fecha_Inicio.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes ingresar fecha de inicio");
            return;
        }
        if (fecha_Fin.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes ingresar fecha de fin");
            return;
        }
        java.sql.Date fechaInicioSQL;
        java.sql.Date fechaFinSQL;
        try {
            fechaInicioSQL = java.sql.Date.valueOf(fecha_Inicio);
            fechaFinSQL = java.sql.Date.valueOf(fecha_Fin);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this,
                    "Formato de fecha inválido. Usa yyyy-MM-dd");
            return;
        }

        Pago pago = new Pago(dpi, tipo, descripcion, monton, fechaInicioSQL, fechaFinSQL);
        dao.crear(pago);
    }//GEN-LAST:event_bt_PagarActionPerformed
    
    public String membresia() {
        MembresiasDao meDao = new MembresiasDao();
        Membresia mem = meDao.buscarPorDpi(dpi);
        int tipo = mem.getTipo();
        String stipo = Utils.getIdTipo(tipo);
        
        return stipo;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Pagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel puerta;
    private javax.swing.JTextPane txt_Descripcion;
    private javax.swing.JTextField txt_FechaFin;
    private javax.swing.JTextField txt_FechaInicio;
    private javax.swing.JTextField txt_Monto;
    // End of variables declaration//GEN-END:variables
}
