package main.interfaz.empleado.inventario;

import java.awt.Color;
import java.awt.Font;
import java.sql.Timestamp;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import main.dao.*;
import main.models.*;
import main.utils.Utils;

/**
 *
 * @author marco
 */
public class lista_Reportes extends javax.swing.JPanel {

    /**
     * Creates new form lista_Reportes
     */
    
    MovimientoDao movDao = new MovimientoDao();
    
    public lista_Reportes() {
        initComponents();
        cargarLista();
        JTableHeader header = tab_Repuestos.getTableHeader();
        header.setBackground(Color.BLUE);
        header.setForeground(Color.black);
        header.setFont(new Font("Free Mono", Font.BOLD, 15));
        tab_Repuestos.setGridColor(Color.WHITE);
        tab_Repuestos.setShowVerticalLines(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        puerta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab_Repuestos = new javax.swing.JTable();
        bt_Cambiar = new javax.swing.JButton();
        bt_Modificar = new javax.swing.JButton();
        bt_Eliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        puerta.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("FreeMono", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(20, 71, 230));
        jLabel1.setText("Lista de cambios y Repuestos equipo");

        tab_Repuestos.setBackground(new java.awt.Color(20, 71, 230));
        tab_Repuestos.setFont(new java.awt.Font("FreeMono", 1, 15)); // NOI18N
        tab_Repuestos.setForeground(new java.awt.Color(255, 255, 255));
        tab_Repuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Cantidad", "Origen", "Destino", "Fecha", "Motivo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab_Repuestos);
        if (tab_Repuestos.getColumnModel().getColumnCount() > 0) {
            tab_Repuestos.getColumnModel().getColumn(0).setMinWidth(80);
            tab_Repuestos.getColumnModel().getColumn(0).setMaxWidth(80);
            tab_Repuestos.getColumnModel().getColumn(2).setMinWidth(80);
            tab_Repuestos.getColumnModel().getColumn(2).setMaxWidth(80);
            tab_Repuestos.getColumnModel().getColumn(3).setMinWidth(100);
            tab_Repuestos.getColumnModel().getColumn(3).setMaxWidth(100);
            tab_Repuestos.getColumnModel().getColumn(4).setMinWidth(100);
            tab_Repuestos.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        bt_Cambiar.setBackground(new java.awt.Color(0, 204, 0));
        bt_Cambiar.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Cambiar.setForeground(new java.awt.Color(0, 0, 0));
        bt_Cambiar.setText("cambio");
        bt_Cambiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CambiarActionPerformed(evt);
            }
        });

        bt_Modificar.setBackground(new java.awt.Color(255, 255, 0));
        bt_Modificar.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Modificar.setForeground(new java.awt.Color(0, 0, 0));
        bt_Modificar.setText("modificar");
        bt_Modificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ModificarActionPerformed(evt);
            }
        });

        bt_Eliminar.setBackground(new java.awt.Color(204, 0, 0));
        bt_Eliminar.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        bt_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        bt_Eliminar.setText("eliminar");
        bt_Eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bt_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_EliminarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Acciones");

        javax.swing.GroupLayout puertaLayout = new javax.swing.GroupLayout(puerta);
        puerta.setLayout(puertaLayout);
        puertaLayout.setHorizontalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(bt_Cambiar)
                        .addGap(52, 52, 52))))
            .addGroup(puertaLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addComponent(bt_Modificar)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Eliminar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        puertaLayout.setVerticalGroup(
            puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(puertaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(puertaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, puertaLayout.createSequentialGroup()
                        .addComponent(bt_Cambiar)
                        .addGap(26, 26, 26)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(puertaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Modificar)
                    .addComponent(bt_Eliminar))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(puerta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_CambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CambiarActionPerformed
        // TODO add your handling code here:
        Utils.mostrarPanel(puerta, new Reportes());
    }//GEN-LAST:event_bt_CambiarActionPerformed

    private void bt_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ModificarActionPerformed
        // TODO add your handling code here:
        String idStr = Utils.selecDatTable(tab_Repuestos, 0, "Seleccione un Equipo en la tabla");
        if (idStr != null) {
            int id_movimiento = Integer.parseInt(idStr);
            Movimiento mov = movDao.buscar(id_movimiento);
            if (mov != null) {
                int id_equipo = mov.getId_equipo();
                int cantidad = mov.getCantidad();
                int origen = mov.getOrigenSuc();
                int destino = mov.getDestinoSuc();
                Timestamp fecha = mov.getFecha_hora();
                String motivo = mov.getMotivo();
                Utils.mostrarPanel(puerta, new mod_Reportes(id_movimiento, id_equipo, 
                        cantidad, origen, destino, fecha, motivo));
            } else {
                JOptionPane.showMessageDialog(this, "Error de ID");
                return;
            }
        }
    }//GEN-LAST:event_bt_ModificarActionPerformed

    private void bt_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_EliminarActionPerformed
        // TODO add your handling code here:
        String idStr = Utils.selecDatTable(tab_Repuestos, 0, "Seleccione un Equipo en la tabla");
        if (idStr != null) {
            int id_movimiento = Integer.parseInt(idStr);
            movDao.eliminar(id_movimiento);
            JOptionPane.showMessageDialog(this, "Repuesto Eliminado");
        }
    }//GEN-LAST:event_bt_EliminarActionPerformed
    
    public void cargarLista() {
        DefaultTableModel modelo = (DefaultTableModel) tab_Repuestos.getModel();
        modelo.setRowCount(0);
        List<Movimiento> lista = movDao.listar();

        for (Movimiento mov : lista) {
            modelo.addRow(new Object[]{
                mov.getId_movimiento(),
                nombre(mov.getId_equipo()),
                mov.getCantidad(),
                Utils.getSucursalNombre(mov.getOrigenSuc()),
                Utils.getSucursalNombre(mov.getDestinoSuc()),
                mov.getFecha_hora(),
                mov.getMotivo()
            });
        }
    }
    
    private String nombre(int id) {
        EquipoDao dao = new EquipoDao();
        Equipo equi = dao.buscar(id);
        if (equi != null) {
            return equi.getNombre();
        } else {
            return "Desconocido";
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Cambiar;
    private javax.swing.JButton bt_Eliminar;
    private javax.swing.JButton bt_Modificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel puerta;
    private javax.swing.JTable tab_Repuestos;
    // End of variables declaration//GEN-END:variables
}
